python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --complex /pi/summer.thyme-umw/ari/ml-test-case-generation/4zzi_publication_placements/4zzi_publication_placementsjm3c00128_si_002.pdb       --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/4zzi_systems     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-0222.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-0222.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-0222     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-0626.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-0626.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-0626     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-0683.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-0683.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-0683     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-0741.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-0741.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-0741     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-5604.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-5604.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-5604     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-5763.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-5763.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-5763     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-6066.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-6066.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-6066     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-ald-1889.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-ald-1889.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-ald-1889     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-ald-1911.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-ald-1911.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-ald-1911     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --receptor /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/rec-ald-4975.pdb  --ligand  /pi/summer.thyme-umw/ari/ml-test-case-generation/5c8s_publication_placements/lig_rec-ald-4975.pdb    --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/5c8s_systems_rec-ald-4975     --min-intervening-atoms 2  --exclude-all-carbon-trios
python /pi/summer.thyme-umw/ari/ml-test-case-generation/prepare_docking_trio_benchmark.py     --complex /pi/summer.thyme-umw/ari/ml-test-case-generation/7sr8_publication_placements/7sr8.pdb       --output-dir /pi/summer.thyme-umw/ari/ml-test-case-generation/generated_cases/7sr8_systems     --min-intervening-atoms 2  --exclude-all-carbon-trios
